name: Build for x64 Windows and upload to an FTP server

on: 
  workflow_dispatch:
    inputs:
      ftpMethod:
        description: "What FTP method to use (FTP or SFTP, default SFTP)"
        default: "sftp"
        required: true
      ftpPort:
        description: "What port to use for the connection (default 22)"
        default: "22"
        required: true

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update the apt repo
        run: |
          sudo add-apt-repository ppa:bitcoin/bitcoin
          sudo apt-get update -y
      - name: Install dependencies
        run: sudo apt-get install libtool libboost-all-dev build-essential autotools-dev automake pkg-config bsdmainutils curl git nsis g++-mingw-w64-x86-64 qtdeclarative5-dev qtbase5-dev qttools5-dev qtdeclarative5-dev qt5-default libzmq3-dev libminiupnpc-dev software-properties-common libssl-dev libevent-dev libdb4.8-dev libdb4.8++-dev -y
      - name: Depends make
        run: |
          #laittaa automaattisen tilan k채ytt채m채채n posixia
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-win32 60
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix 90
          sudo update-alternatives --config x86_64-w64-mingw32-gcc 
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-win32 60
          sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix 90
          sudo update-alternatives --config x86_64-w64-mingw32-g++
          
          cd depends
          sudo make HOST=x86_64-w64-mingw32
          cd ..
      - name: Autoconfig
        run:  sudo ./autogen.sh
      - name: Configure 
        run: sudo CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
      - name: Make
        run: sudo make
      - name: Make installer
        run: | 
          sudo make deploy
          ls -R
      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env: 
        #credentials are stored in the repository secrets separated by "|" in format "server|username|password".
          FTP_SERVER: $(cut -d'|' -f1 <<< "${{ secrets.FTP_CREDS }}")
          FTP_USERNAME: $(cut -d'|' -f2 <<< "${{ secrets.FTP_CREDS }}")
          FTP_PASSWORD: $(cut -d'|' -f3 <<< "${{ secrets.FTP_CREDS }}")
          METHOD: "${{ github.event.inputs.ftpMethod }}"
          PORT: "${{ github.event.inputs.ftpPort }}"
          ARGS: --include-glob=*.exe
